name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application image
        working-directory: dev-web/App
        run: docker build -t innovatech-web:${{ github.sha }} .

      - name: Verify application image
        run: docker image inspect innovatech-web:${{ github.sha }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 |
          docker login --username AWS --password-stdin 639962671417.dkr.ecr.eu-central-1.amazonaws.com

      - name: Tag application image
        run: |
          docker tag innovatech-web:${{ github.sha }} \
            639962671417.dkr.ecr.eu-central-1.amazonaws.com/innovatech-web:${{ github.sha }}

      - name: Push application image
        run: |
          docker push \
            639962671417.dkr.ecr.eu-central-1.amazonaws.com/innovatech-web:${{ github.sha }}