name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application image
        working-directory: dev-web/App
        run: docker build -t innovatech-web:${{ github.sha }} .

      - name: Verify application image
        run: docker image inspect innovatech-web:${{ github.sha }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 |
          docker login --username AWS --password-stdin 639962671417.dkr.ecr.eu-central-1.amazonaws.com

      - name: Tag application image
        run: |
          docker tag innovatech-web:${{ github.sha }} \
            639962671417.dkr.ecr.eu-central-1.amazonaws.com/innovatech-web:${{ github.sha }}

      - name: Push application image
        run: |
          docker push \
            639962671417.dkr.ecr.eu-central-1.amazonaws.com/innovatech-web:${{ github.sha }}

      - name: Download current ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition dev-web \
            --query taskDefinition \
            --output json > task-definition.json

      - name: Update application image
        run: |
          jq --arg IMAGE \
            "639962671417.dkr.ecr.eu-central-1.amazonaws.com/innovatech-web:${{ github.sha }}" \
            '.containerDefinitions |= map(
              if .name == "web"
              then .image = $IMAGE
              else .
              end
            ) |
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )' \
            task-definition.json > new-task-definition.json

      - name: Register new ECS task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json

      - name: Deploy new task definition
        run: |
          TASK_DEFINITION=$(aws ecs describe-task-definition \
            --task-definition dev-web \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          aws ecs update-service \
            --cluster dev-cluster \
            --service dev-web-service \
            --task-definition "$TASK_DEFINITION" \
            --region eu-central-1